print("##############################")
print("#                            #")
print("#   afrian pradipta rizky    #")
print("#       2410817210028        #")
print("#                            #")
print("##############################")